### ISSUE TITLE
Error from cp_nomination_details

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#490]
```
Error from cp_nomination_details in 🏅community-promotions called by Conshmea 🐢: The check functions for command 'cp_nomination_details' failed.

Task exception was never retrieved

future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /usr/local/lib/python3.10/site-packages/discord/app_commands/tree.py:1089> exception=InteractionResponded('This interaction has already been responded to before')>

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1242, in _call

    await command._invoke_with_namespace(interaction, namespace)

  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 884, in _invoke_with_namespace

    raise CheckFailure(f'The check functions for command {self.name!r} failed.')

discord.app_commands.errors.CheckFailure: The check functions for command 'cp_nomination_details' failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1091, in wrapper

    await self._call(interaction)

  File "/usr/local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1246, in _call

    await self.on_error(interaction, e)

  File "/usr/local/lib/python3.10/site-packages/ptn/missionalertbot/modules/helpers.py", line 48, in on_app_command_error

    return await interaction.response.send_message(error, ephemeral=True)

  File "/usr/local/lib/python3.10/site-packages/discord/interactions.py", line 743, in send_message

    raise InteractionResponded(self._parent)

discord.errors.InteractionResponded: This interaction has already been responded to before

Mission Alert Bot has disconnected from discord server, version: 2.0.0.
```

Calling user did not have required roles but this should be handled cleanly.

**Comment by cimspin** [comment]
Fixed in 2.1.0
