### ISSUE TITLE
WMM task fails with more than one commodity at low stock

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/MissionAlertBot#665]
```Market data for P.T.N. CANNOCK CHASE: [{'id': 128049154, 'categoryname': 'Metals', 'name': 'Gold', 'stock': 152, 'buyPrice': 69029, 'sellPrice': 0, 'demand': 0, 'legality': '', 'meanPrice': 0, 'demandBracket': '', 'stockBracket': 2, 'locName': 'Gold'}, {'id': 128049156, 'categoryname': 'Minerals', 'name': 'Bertrandite', 'stock': 23668, 'buyPrice': 41565, 'sellPrice': 0, 'demand': 0, 'legality': '', 'meanPrice': 0, 'demandBracket': '', 'stockBracket': 2, 'locName': 'Bertrandite'}, {'id': 128049157, 'categoryname': 'Minerals', 'name': 'Indite', 'stock': 79, 'buyPrice': 34667, 'sellPrice': 0, 'demand': 0, 'legality': '', 'meanPrice': 0, 'demandBracket': '', 'stockBracket': 2, 'locName': 'Indite'}, {'id': 128066403, 'categoryname': 'NonMarketable', 'name': 'Drones', 'stock': 999999, 'buyPrice': 101, 'sellPrice': 101, 'demand': 9999999, 'legality': '', 'meanPrice': 101, 'demandBracket': 2, 'stockBracket': 2, 'locName': 'Limpet'}]
Generating low stock warning for P.T.N. CANNOCK CHASE to DM to owner
Low stock DM sent to grandechungo
Received data: MALERBA ['Gold'] 1 TFW-WVH
wmm_stock error(). task has failed.
wmm_stock after_loop(). task has failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ptn/missionalertbot/modules/BackgroundTasks.py", line 320, in wmm_stock
    notification_status = json.loads(carrier.notification_status) if carrier.notification_status else []
  File "/usr/local/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list```

**Comment by cimspin** [comment]
Fixed in #666
